# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_cards_details.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(330, 231)
        icon = QIcon()
        icon.addFile(u"icons/pagamento-com-cartao-de-credito.ico", QSize(), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(9, 9, 312, 211))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.save_button = QPushButton(self.frame)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(120, 184, 75, 24))
        self.save_button.setMaximumSize(QSize(100, 16777215))
        font = QFont()
        font.setBold(True)
        self.save_button.setFont(font)
        self.save_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.order_label = QLabel(self.frame)
        self.order_label.setObjectName(u"order_label")
        self.order_label.setGeometry(QRect(111, -5, 84, 32))
        self.order_label.setMinimumSize(QSize(0, 10))
        self.order_label.setMaximumSize(QSize(16777215, 100))
        font1 = QFont()
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setUnderline(True)
        self.order_label.setFont(font1)
        self.order_label.setStyleSheet(u"QLabel {\n"
"	color: red;\n"
"}")
        self.order_label.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 53, 95, 10))
        self.label_6.setMaximumSize(QSize(16777215, 10))
        self.label_6.setFont(font)
        self.cashier_lineEdit = QLineEdit(self.frame)
        self.cashier_lineEdit.setObjectName(u"cashier_lineEdit")
        self.cashier_lineEdit.setGeometry(QRect(10, 72, 95, 22))
        self.cashier_lineEdit.setMaximumSize(QSize(100, 16777215))
        self.cashier_lineEdit.setReadOnly(True)
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(111, 50, 71, 16))
        self.label_7.setMaximumSize(QSize(16777215, 20))
        self.label_7.setFont(font)
        self.cash_flow_lineEdit = QLineEdit(self.frame)
        self.cash_flow_lineEdit.setObjectName(u"cash_flow_lineEdit")
        self.cash_flow_lineEdit.setGeometry(QRect(111, 72, 95, 22))
        self.cash_flow_lineEdit.setMaximumSize(QSize(100, 16777215))
        self.cash_flow_lineEdit.setReadOnly(True)
        self.order_value_lineEdit = QLineEdit(self.frame)
        self.order_value_lineEdit.setObjectName(u"order_value_lineEdit")
        self.order_value_lineEdit.setGeometry(QRect(212, 72, 95, 22))
        self.order_value_lineEdit.setMaximumSize(QSize(100, 16777215))
        self.order_value_lineEdit.setReadOnly(False)
        self.installments_comboBox = QComboBox(self.frame)
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.addItem("")
        self.installments_comboBox.setObjectName(u"installments_comboBox")
        self.installments_comboBox.setGeometry(QRect(245, 116, 51, 22))
        self.installments_comboBox.setMaximumSize(QSize(150, 16777215))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.installments_comboBox.setFont(font2)
        self.card_flag_comboBox = QComboBox(self.frame)
        self.card_flag_comboBox.addItem("")
        self.card_flag_comboBox.setObjectName(u"card_flag_comboBox")
        self.card_flag_comboBox.setGeometry(QRect(12, 116, 111, 22))
        self.card_flag_comboBox.setMaximumSize(QSize(150, 16777215))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(245, 100, 51, 10))
        self.label_5.setMaximumSize(QSize(16777215, 10))
        self.label_5.setFont(font)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(135, 100, 90, 10))
        self.label_4.setMaximumSize(QSize(90, 10))
        self.label_4.setFont(font)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 100, 95, 10))
        self.label_3.setMaximumSize(QSize(16777215, 10))
        self.label_3.setFont(font)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(212, 53, 20, 10))
        self.label_2.setMaximumSize(QSize(20, 10))
        self.label_2.setFont(font)
        self.nsu_lineEdit = QLineEdit(self.frame)
        self.nsu_lineEdit.setObjectName(u"nsu_lineEdit")
        self.nsu_lineEdit.setGeometry(QRect(28, 155, 113, 22))
        self.authorization_lineEdit = QLineEdit(self.frame)
        self.authorization_lineEdit.setObjectName(u"authorization_lineEdit")
        self.authorization_lineEdit.setGeometry(QRect(172, 155, 113, 22))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 140, 61, 16))
        self.label.setFont(font)
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(180, 140, 91, 16))
        self.label_8.setFont(font)
        self.date_text_label = QLabel(self.frame)
        self.date_text_label.setObjectName(u"date_text_label")
        self.date_text_label.setGeometry(QRect(84, 25, 91, 20))
        self.date_text_label.setFont(font)
        self.sale_date = QLabel(self.frame)
        self.sale_date.setObjectName(u"sale_date")
        self.sale_date.setGeometry(QRect(169, 25, 91, 20))
        self.sale_date.setFont(font)
        self.transaction_type_comboBox = QComboBox(self.frame)
        self.transaction_type_comboBox.addItem("")
        self.transaction_type_comboBox.addItem("")
        self.transaction_type_comboBox.addItem("")
        self.transaction_type_comboBox.setObjectName(u"transaction_type_comboBox")
        self.transaction_type_comboBox.setGeometry(QRect(135, 116, 90, 22))
        self.transaction_type_comboBox.setMaximumSize(QSize(150, 16777215))
        self.delete_button = QPushButton(self.frame)
        self.delete_button.setObjectName(u"delete_button")
        self.delete_button.setGeometry(QRect(275, 2, 31, 24))
        self.delete_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u"icons/delete.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.delete_button.setIcon(icon1)
        self.delete_button.setFlat(True)
        self.plus_card_button = QPushButton(self.frame)
        self.plus_card_button.setObjectName(u"plus_card_button")
        self.plus_card_button.setGeometry(QRect(10, 4, 31, 24))
        self.plus_card_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.plus_card_button.setToolTipDuration(-1)
        icon2 = QIcon()
        icon2.addFile(u"icons/mais.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.plus_card_button.setIcon(icon2)
        self.plus_card_button.setFlat(True)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.save_button.setText(QCoreApplication.translate("Form", u"Salvar", None))
        self.order_label.setText(QCoreApplication.translate("Form", u"202321", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Caixa", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Mov. Caixa", None))
        self.installments_comboBox.setItemText(0, QCoreApplication.translate("Form", u"1", None))
        self.installments_comboBox.setItemText(1, QCoreApplication.translate("Form", u"2", None))
        self.installments_comboBox.setItemText(2, QCoreApplication.translate("Form", u"3", None))
        self.installments_comboBox.setItemText(3, QCoreApplication.translate("Form", u"4", None))
        self.installments_comboBox.setItemText(4, QCoreApplication.translate("Form", u"5", None))
        self.installments_comboBox.setItemText(5, QCoreApplication.translate("Form", u"6", None))
        self.installments_comboBox.setItemText(6, QCoreApplication.translate("Form", u"7", None))
        self.installments_comboBox.setItemText(7, QCoreApplication.translate("Form", u"8", None))
        self.installments_comboBox.setItemText(8, QCoreApplication.translate("Form", u"9", None))
        self.installments_comboBox.setItemText(9, QCoreApplication.translate("Form", u"10", None))
        self.installments_comboBox.setItemText(10, QCoreApplication.translate("Form", u"11", None))
        self.installments_comboBox.setItemText(11, QCoreApplication.translate("Form", u"12", None))

        self.card_flag_comboBox.setItemText(0, QCoreApplication.translate("Form", u"Selecione", None))

        self.label_5.setText(QCoreApplication.translate("Form", u"Parcelas", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Modalidade", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Bandeira", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"R$", None))
        self.label.setText(QCoreApplication.translate("Form", u"DOC / NSU", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"AUTORIZA\u00c7\u00c3O", None))
        self.date_text_label.setText(QCoreApplication.translate("Form", u"Data da venda: ", None))
        self.sale_date.setText(QCoreApplication.translate("Form", u"24/02/18", None))
        self.transaction_type_comboBox.setItemText(0, QCoreApplication.translate("Form", u"Selecione", None))
        self.transaction_type_comboBox.setItemText(1, QCoreApplication.translate("Form", u"Cr\u00e9dito", None))
        self.transaction_type_comboBox.setItemText(2, QCoreApplication.translate("Form", u"D\u00e9bito", None))

#if QT_CONFIG(tooltip)
        self.delete_button.setToolTip(QCoreApplication.translate("Form", u"Excluir pagamento", None))
#endif // QT_CONFIG(tooltip)
        self.delete_button.setText("")
#if QT_CONFIG(tooltip)
        self.plus_card_button.setToolTip(QCoreApplication.translate("Form", u"Pagamento com mais de um cart\u00e3o", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.plus_card_button.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.plus_card_button.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.plus_card_button.setText("")
    # retranslateUi

